### PR TITLE
Add jvm argument --add-modules java.xml.bind when java version is 9

### PR DESCRIPTION
**Pull request by benrobot**
Add jvm argument --add-modules java.xml.bind when java version is 9
Fix: #237

### CODE REVIEW

**Comment by mfilippov** [comment]
@benrobot Are you hardcoded only version 9? The latest stable Java is 11.

**Comment by OttoG** [comment]
While this workaround may be useful for Java 9 and 10, the java.xml.bind API (JAXB) was unfortunately removed from Java 11. See the https://stackoverflow.com/a/43574427/2416627 answer to a similar discussion.

I found that under Java 12, a sufficient workaround was to download the current version of the jaxb-api artifact from Maven as a JAR:

https://search.maven.org/search?q=g:javax.xml.bind%20AND%20a:jaxb-api

If the downloaded file (currently jaxb-api-2.4.0-b180830.0359.jar) is placed in the lib directory for TEE, the tf command starts working under JDK 12.

The proper fix should be to include this JAR as a distributed dependency library in the compiled TEE distributions.

**Comment by ForNeVeR** [comment]
Another workaround is to define an environment variable `TF_NOTELEMETRY=TRUE`. Only the telemetry functions require java.xml.bind here, so no telemetry = no problems.

**Comment by brunoborges** [comment]
The dependency (JAR) for XML can be downloaded and shipped with the tool, and set in the classpath as usual. No need to use modules.

**Pull request closed without merging**
