### PR TITLE
Update CLC link in ReadMe

### PR DESCRIPTION
**Pull request by leantk**
Issue #141 found a broken link in the ReadMe for the CLC download

### CODE REVIEW

**Comment by DavidStaheli** [comment]
Looks good!  I just updated your branch to remove "en-us" from the link so that the site dynamically chooses the user's preferred locale instead of going straight to English-US.

**Comment by paulvi** [comment]
> Microsoft Team Explorer Everywhere 2015 (Out-of-date versions 14.0.2-14.0.3 for legacy systems)

Such title is not motivating.

Is it really the one to use?

**Comment by DavidStaheli** [comment]
Hi @paulvi, yes, there is some text a bit further down (sadly not noticeable?) that explains where to get the latest downloads:  https://github.com/Microsoft/team-explorer-everywhere/releases

**Comment by DavidStaheli** [comment]
We'll update the readme.md though, to not lead people through the loop of links anymore.

**Comment by paulvi** [comment]
Great

**Pull request merged**
